FROM python:3.12-slim

WORKDIR /

COPY requirements.txt /backend/
RUN pip install --no-cache-dir -r /backend/requirements.txt

COPY app/ /backend/app/

EXPOSE 8000

CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
